<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_01</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>706fbba5-145d-4d36-80e7-78e97d5f5496</testSuiteGuid>
   <testCaseLink>
      <guid>d66d283f-497a-4a64-9d54-e645c2d8a900</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_001</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1f37c30-6d51-4a57-8ae0-da0d04088e7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0037e430-e38f-49e5-8826-615a21d3be4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4516e61-3649-4b48-b186-552b49673342</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c73d4441-bcfd-452a-8255-8fa008f2e8ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_002</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be698343-6479-4603-8932-e7fab9a94bd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dfa21f3-ba87-4566-b3c3-ffcc52499820</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74075ac8-9b4c-4425-8d5d-ac18a4a9e74e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c68b27d8-d79f-4cbe-a343-ca1d9941adb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_003</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b6bcb9cb-122e-4557-ada3-9507401908f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_004</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>17e87ed4-5cd6-4c86-ad6c-ad6661322aa9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_05</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
